#!/bin/bash

logger "Starting ${NAME_OF_THE_EXECUTABLE} service"

BNAME=`basename $0 .sh`
DNAME=`dirname $0`

# read central config file
. ${DNAME}/tools.conf

MJPGSTREAMER_HOME="${PATH_TO_EXECUTABLE}"
MJPGSTREAMER_INPUT_USB="input_uvc.so"
MJPGSTREAMER_INPUT_RASPICAM="input_raspicam.so"

# init configuration
camera="auto"
camera_usb_options="-r 640x480 -f 10"
camera_raspi_options="-fps 20"

#if [ -e "/boot/octopi.txt" ]; then
#    source "/boot/octopi.txt"
#fi

# runs MJPG Streamer, using the provided input_lib plugin + configuration
function runMjpgStreamer {
    local input_lib=$1
    local cam_options=$2

    pushd $MJPGSTREAMER_HOME
    logger "Running ./mjpg_streamer -o \"output_http.so -w ./www\" -i \"$input_lib\""

    # export the path where the input and output libraries are located
    export_ld_library_path "${input_lib} output_http.so"

    # start the test by executing the program with parameters
    #${NAME_OF_THE_EXECUTABLE} -o "output_http.so -w ./www" -i "input_raspicam.so -fps 5"
    #${NAME_OF_THE_EXECUTABLE} -o "output_http.so -w ./www" -i "input_raspicam.so -fps 20"
    ${EXECUTABLE_FILE} -o "output_http.so -w ./www" -i "$input_lib ${cam_options}"
    popd
}

# starts up the RasPiCam
function startRaspi {
    logger "Starting Raspberry Pi camera"
    runMjpgStreamer $MJPGSTREAMER_INPUT_RASPICAM $camera_raspi_options
}

# starts up the USB webcam
function startUsb {
    logger "Starting USB webcam"
    runMjpgStreamer $MJPGSTREAMER_INPUT_USB $camera_usb_options
}

# we need this to prevent the later calls to vcgencmd from blocking
# I have no idea why, but that's how it is...
vcgencmd version

# echo configuration
logger "${NAME_OF_THE_EXECUTABLE}: camera: $camera"
logger "${NAME_OF_THE_EXECUTABLE}: usb options: $camera_usb_options"
logger "${NAME_OF_THE_EXECUTABLE}: raspi options: $camera_raspi_options"

# keep mjpg streamer running if some camera is attached
while true; do
    if [ -e "/dev/video0" ] && { [ "$camera" = "auto" ] || [ "$camera" = "usb" ] ; }; then
        startUsb
    elif [ "`vcgencmd get_camera`" = "supported=1 detected=1" ] && { [ "$camera" = "auto" ] || [ "$camera" = "raspi" ] ; }; then
        startRaspi
    fi

    sleep 120
done
